language: csharp
sudo: required
dist: xenial
dotnet: 2.2
mono: none
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - CLI_VERSION=latest
    - ASPNETCORE_ENVIRONMENT="Production"
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
    - REPO_COMMIT_AUTHOR=$(git show -s --pretty=format:"%cn")
    - REPO_COMMIT_AUTHOR_EMAIL=$(git show -s --pretty=format:"%ce")
    - REPO_COMMIT_MESSAGE=$(git show -s --pretty=format:"%s")
    - PATH="$PATH:/home/travis/.dotnet/tools"
install:
 - dotnet tool install -g coveralls.net --version 1.0.0
script:
 - dotnet restore
 - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover tests/Integration/Integration.csproj 
 
after_success:
  - csmacnz.Coveralls --opencover -i ./tests/Integration/coverage.xml --repoToken $COVERALLS_REPO_TOKEN --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitAuthor "$REPO_COMMIT_AUTHOR" --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID  --serviceName "travis-ci" --useRelativePaths
  - docker build . -t "$DOCKER_HUB_ORG_OR_USER_NAME"/"$DOCKER_HUB_REPO_NAME":"$TRAVIS_BUILD_NUMBER" -t "$DOCKER_HUB_ORG_OR_USER_NAME"/"$DOCKER_HUB_REPO_NAME":latest -f ./Dockerfile
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push "$DOCKER_HUB_ORG_OR_USER_NAME"/"$DOCKER_HUB_REPO_NAME";
    fi
