language: csharp
sudo: required
dist: trusty
dotnet: 2.1
mono: none
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - CLI_VERSION=latest
    - ASPNETCORE_ENVIRONMENT="tests"
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
install:
 - dotnet tool install coveralls.net --version 1.0.0 --tool-path tools
script:
 - dotnet restore
 - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover tests/Integration/Integration.csproj 
 - docker build . -t "$DOCKER_HUB_ORG_OR_USER_NAME"/"$DOCKER_HUB_REPO_NAME":"$TRAVIS_BUILD_NUMBER" -t "$DOCKER_HUB_ORG_OR_USER_NAME"/"$DOCKER_HUB_REPO_NAME":latest -f ./Dockerfile
 
after_success:
  - ./tools/csmacnz.Coveralls --opencover -i ./tests/Integration/coverage.xml --useRelativePaths
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push "$DOCKER_HUB_ORG_OR_USER_NAME"/"$DOCKER_HUB_REPO_NAME";
    fi
