language: csharp
sudo: required
dist: trusty
dotnet: 2.0.0
mono: none
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - CLI_VERSION=latest
    - ASPNETCORE_ENVIRONMENT="tests"
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
script:
 - dotnet restore
 - dotnet test tests/Integration/Integration.csproj
branches:
  only:
    - master
    - dev
notifications: